name: Web API Deploy Pipeline
on:
  push:
    paths:
      - 'cicd-section/api/**'

env:
  AWS_REGION: us-west-2
  ECS_CLUSTER: my-app-cluster
  ECS_SERVICE: my-app-api-service
  ECS_REPOSITORY: my-app-api
  ECS_TASK_DEFINITION_API: cicd-section/.aws/task-def-api.json

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
      - run: echo "Github Actions!!"
  goodbye-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Goodbye, Github Actions."